"""
Legal disclaimer components - CRITICAL for compliance.

Disclaimers must appear on EVERY page:
1. Modal on first visit (must accept to continue)
2. Banner at top of every page
3. Footer on every page
4. Inline warning on predictions
"""

import streamlit as st
from config.settings import Constants


def show_disclaimer_modal() -> None:
    """
    Show first-time user disclaimer modal.

    CRITICAL: This must be called at the start of every page.
    Blocks app until user accepts disclaimer.
    """
    if "disclaimer_accepted" not in st.session_state:
        st.session_state.disclaimer_accepted = False

    if not st.session_state.disclaimer_accepted:
        st.markdown("""
        <style>
        .disclaimer-modal {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            padding: 30px;
            border-radius: 15px;
            border: 2px solid #e94560;
            margin: 20px 0;
        }
        .disclaimer-title {
            color: #e94560;
            font-size: 28px;
            font-weight: bold;
            margin-bottom: 20px;
        }
        .disclaimer-content {
            color: #eee;
            font-size: 16px;
            line-height: 1.8;
        }
        .disclaimer-bullet {
            color: #0f3460;
            background: #e94560;
            padding: 2px 8px;
            border-radius: 4px;
            margin-right: 10px;
        }
        </style>
        """, unsafe_allow_html=True)

        st.warning("**Please read and accept the legal disclaimer to continue**")

        st.markdown("""
        ### Legal Disclaimer

        **The Earnings Hunter** provides AI-generated analysis for **educational purposes only**.

        #### This tool does NOT provide:
        - Financial advice
        - Investment recommendations
        - Trading signals
        - Guaranteed predictions

        #### You acknowledge that:
        - All investment decisions are your own responsibility
        - AI predictions can be inaccurate
        - You may lose money by acting on this information
        - You should consult a licensed professional for financial advice
        - Past performance does not guarantee future results

        #### Important:
        The predictions and analyses shown are generated by machine learning models
        trained on historical data. Markets are unpredictable, and no model can
        guarantee accuracy. Always do your own research (DYOR).
        """)

        st.markdown("---")

        # Hebrew disclaimer
        st.markdown("""
        ### הצהרה משפטית (בעברית)

        כלי זה מיועד **למטרות לימודיות ומידעיות בלבד**.
        אין לראות בתוכן המוצג ייעוץ פיננסי, המלצת השקעה או המלצת מסחר.
        יש להתייעץ עם יועץ השקעות מורשה לפני קבלת החלטות השקעה.
        """)

        st.markdown("---")

        col1, col2 = st.columns(2)

        with col1:
            if st.button("I Understand and Accept", type="primary", use_container_width=True):
                st.session_state.disclaimer_accepted = True
                st.rerun()

        with col2:
            if st.button("Exit", use_container_width=True):
                st.stop()

        st.stop()  # Prevent rest of app from loading


def show_disclaimer_banner() -> None:
    """
    Show persistent disclaimer banner at top of page.

    CRITICAL: Must be called after modal, before page content.
    """
    st.markdown("""
    <style>
    .disclaimer-banner {
        background: linear-gradient(90deg, #FF6B6B, #FF8E53);
        color: white;
        padding: 12px 20px;
        border-radius: 8px;
        text-align: center;
        font-weight: bold;
        margin-bottom: 20px;
        box-shadow: 0 2px 10px rgba(255,107,107,0.3);
    }
    .disclaimer-icon {
        margin-right: 10px;
    }
    </style>
    """, unsafe_allow_html=True)

    st.markdown(f"""
    <div class="disclaimer-banner">
        <span class="disclaimer-icon">⚠️</span>
        {Constants.DISCLAIMER_BANNER}
    </div>
    """, unsafe_allow_html=True)


def show_disclaimer_footer() -> None:
    """
    Show footer disclaimer at bottom of page.

    Should be called at the end of every page.
    """
    st.markdown("---")

    st.markdown("""
    <style>
    .disclaimer-footer {
        background: #2D2D2D;
        color: #AAAAAA;
        padding: 20px;
        border-radius: 8px;
        font-size: 12px;
        margin-top: 30px;
        line-height: 1.6;
    }
    .disclaimer-footer strong {
        color: #FF6B6B;
    }
    .disclaimer-footer-hebrew {
        margin-top: 15px;
        padding-top: 15px;
        border-top: 1px solid #444;
        direction: rtl;
        text-align: right;
    }
    </style>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="disclaimer-footer">
        <strong>⚠️ Important Legal Notice:</strong><br><br>
        The Earnings Hunter is an educational tool designed to demonstrate AI/ML capabilities
        in financial data analysis. <strong>This is NOT financial advice.</strong><br><br>
        The predictions, analyses, and insights provided by this platform should NOT be used
        as the sole basis for any investment decision.<br><br>
        • Past performance does not guarantee future results<br>
        • AI predictions can be wrong and markets are unpredictable<br>
        • Always do your own research (DYOR)<br>
        • Consult with a qualified financial advisor before investing<br><br>
        By using this tool, you acknowledge that you understand and accept these terms.

        <div class="disclaimer-footer-hebrew">
            <strong>⚠️ הבהרה משפטית:</strong><br>
            כלי זה מיועד למטרות לימודיות ומידעיות בלבד.
            אין לראות בתוכן המוצג ייעוץ פיננסי, המלצת השקעה או המלצת מסחר.
            יש להתייעץ עם יועץ השקעות מורשה לפני קבלת החלטות השקעה.
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div style="text-align: center; color: #666; margin-top: 20px; font-size: 11px;">
        © 2024-2026 The Earnings Hunter | For Educational Purposes Only
    </div>
    """, unsafe_allow_html=True)


def show_prediction_with_warning(
    prediction: str,
    confidence: float = None,
    show_probabilities: bool = False,
    probabilities: dict = None
) -> None:
    """
    Display prediction with inline disclaimer warning.

    Args:
        prediction: The prediction label (Growth/Stagnation/Risk)
        confidence: Prediction confidence (0-1)
        show_probabilities: Whether to show probability breakdown
        probabilities: Dict of class probabilities
    """
    # Color mapping
    colors = {
        "Growth": ("#00C851", "#007E33"),
        "Stagnation": ("#ffbb33", "#FF8800"),
        "Risk": ("#ff4444", "#CC0000")
    }

    bg_color, border_color = colors.get(prediction, ("#888", "#666"))

    st.markdown(f"""
    <style>
    .prediction-box {{
        background: linear-gradient(135deg, {bg_color}22, {bg_color}11);
        border: 2px solid {border_color};
        border-radius: 12px;
        padding: 20px;
        margin: 15px 0;
    }}
    .prediction-label {{
        font-size: 14px;
        color: #888;
        margin-bottom: 5px;
    }}
    .prediction-value {{
        font-size: 32px;
        font-weight: bold;
        color: {bg_color};
    }}
    .prediction-confidence {{
        font-size: 14px;
        color: #aaa;
        margin-top: 5px;
    }}
    .prediction-warning {{
        background: #FF6B6B22;
        border: 1px solid #FF6B6B;
        border-radius: 6px;
        padding: 8px 12px;
        margin-top: 15px;
        font-size: 12px;
        color: #FF6B6B;
    }}
    </style>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns([3, 1])

    with col1:
        confidence_text = f"{confidence:.0%}" if confidence else "N/A"
        st.markdown(f"""
        <div class="prediction-box">
            <div class="prediction-label">Model Prediction</div>
            <div class="prediction-value">{prediction}</div>
            <div class="prediction-confidence">Confidence: {confidence_text}</div>
            <div class="prediction-warning">
                🔔 This is NOT financial advice. The prediction is for educational purposes only.
            </div>
        </div>
        """, unsafe_allow_html=True)

    with col2:
        st.markdown("""
        <div style="
            background: #FF6B6B22;
            border-radius: 8px;
            padding: 15px;
            text-align: center;
            height: 100%;
        ">
            <div style="font-size: 40px; margin-bottom: 10px;">⚠️</div>
            <div style="font-size: 12px; color: #FF6B6B; font-weight: bold;">
                NOT<br>FINANCIAL<br>ADVICE
            </div>
        </div>
        """, unsafe_allow_html=True)

    # Show probabilities if requested
    if show_probabilities and probabilities:
        st.markdown("**Probability Breakdown:**")
        for label, prob in probabilities.items():
            st.progress(prob, text=f"{label}: {prob:.1%}")


def show_inline_warning() -> None:
    """Show small inline warning for use near any prediction/recommendation."""
    st.caption("🔔 *Not financial advice - for educational purposes only*")


def ensure_disclaimers() -> None:
    """
    Convenience function to ensure all required disclaimers are shown.

    Call this at the start of every page:
        from app.components.disclaimer import ensure_disclaimers
        ensure_disclaimers()
    """
    show_disclaimer_modal()
    show_disclaimer_banner()
